"""
Main Query Interface
"""

from database.neo4j_db import Neo4jGraph
from database.queries.onboarding_queries import OnboardingQueries
from database.queries.analysis_queries import AnalysisQueries
from database.queries.refactoring_queries import RefactoringQueries

from config.config import NEO4J_URI, NEO4J_USERNAME, NEO4J_PASSWORD
from typing import Optional
import logging

logger = logging.getLogger(__name__)


class Query:

    def __init__(
            self,
            uri: Optional[str] = None,
            username: Optional[str] = None,
            password: Optional[str] = None,
            database: Optional[str] = None
    ):
        # Use config defaults if not provided
        uri = uri or NEO4J_URI
        username = username or NEO4J_USERNAME
        password = password or NEO4J_PASSWORD

        # Connect to Neo4j
        self.db = Neo4jGraph(uri, username, password, database)

        # Initialize query modules
        self.onboarding = OnboardingQueries(self.db)
        self.refactoring = RefactoringQueries(self.db)
        self.analysis = AnalysisQueries(self.db)

        logger.info("CodeCompass initialized")

    def close(self):
        """Close database connection"""
        self.db.close()
        logger.info("CodeCompass connection closed")

    def __enter__(self):
        """Context manager entry"""
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit"""
        self.close()

    # ========== CONVENIENCE METHODS ==========
    # These delegate to query modules for easier access

    # Onboarding
    def get_entry_points(self, limit: int = 10):
        """Find good starting points for new developers"""
        return self.onboarding.get_entry_points(limit)

    def get_learning_path(self, limit: int = 20):
        """Generate learning path from simple to complex"""
        return self.onboarding.get_learning_path(limit)

    def get_file_summary(self, file_path: str):
        """Get summary of what's in a file"""
        return self.onboarding.get_file_summary(file_path)

    def get_function_context(self, function_name: str):
        """Get full context for a function"""
        return self.onboarding.get_function_context(function_name)

    # Refactoring
    def get_blast_radius(self, function_name: str, max_depth: int = 5):
        """Find what breaks if this function changes"""
        return self.refactoring.get_blast_radius(function_name, max_depth)

    def find_dead_code(self):
        """Find functions that are never called"""
        return self.refactoring.find_dead_code()

    def find_circular_dependencies(self, max_depth: int = 5):
        """Find circular call chains"""
        return self.refactoring.find_circular_dependencies(max_depth)

    def find_god_functions(self, min_calls: int = 10, min_lines: int = 100):
        """Find overly complex functions"""
        return self.refactoring.find_god_functions(min_calls, min_lines)

    # Analysis
    def get_most_called_functions(self, limit: int = 10):
        """Find most frequently called functions"""
        return self.analysis.get_most_called_functions(limit)

    def get_complexity_hotspots(self, limit: int = 10):
        """Find files with highest complexity"""
        return self.analysis.get_complexity_hotspots(limit)

    def get_codebase_stats(self):
        """Get overall codebase statistics"""
        return self.analysis.get_codebase_stats()

    # ========== REPORT GENERATION ==========

    def generate_onboarding_report(self, limit: int = 10) -> str:
        """
        Generate markdown onboarding report for new developers

        Args:
            limit: Number of items per section

        Returns:
            Markdown formatted report
        """
        report = ["# Codebase Onboarding Guide\n"]
        report.append("*Generated by CodeCompass*\n")

        # Stats
        stats = self.get_codebase_stats()
        report.append("## Overview\n")
        report.append(f"- **Files:** {stats.get('files', 0)}")
        report.append(f"- **Classes:** {stats.get('classes', 0)}")
        report.append(f"- **Functions:** {stats.get('functions', 0)}")
        report.append(f"- **Methods:** {stats.get('methods', 0)}\n")

        # Entry points
        entry_points = self.get_entry_points(limit)
        if entry_points:
            report.append("## Where to Start\n")
            report.append("These are good entry points for understanding the codebase:\n")
            for i, func in enumerate(entry_points, 1):
                report.append(f"{i}. **{func['name']}** in `{func['file']}`:{func['line']}")
                report.append(f"   - Called by {func['called_by']} functions")
                report.append(f"   - Calls {func['calls_out']} other functions\n")

        # Learning path
        learning_path = self.get_learning_path(limit)
        if learning_path:
            report.append("## Suggested Learning Path\n")
            report.append("Study these functions in order (simple → complex):\n")
            for i, func in enumerate(learning_path, 1):
                report.append(f"{i}. **{func['name']}** (`{func['file']}`:{func['line']}) - Complexity: {func['complexity_score']}")

        return "\n".join(report)

    def generate_refactoring_report(self, limit: int = 10) -> str:
        """
        Generate markdown refactoring analysis report

        Args:
            limit: Number of items per section

        Returns:
            Markdown formatted report
        """
        report = ["# Refactoring Analysis Report\n"]
        report.append("*Generated by CodeCompass*\n")

        # Dead code
        dead_code = self.find_dead_code()
        if dead_code:
            report.append(f"## Dead Code ({len(dead_code)} functions)\n")
            report.append("These functions are never called and may be safe to remove:\n")
            for func in dead_code[:limit]:
                report.append(f"- **{func['name']}** in `{func['file']}`:{func['line']}")

        # God functions
        god_functions = self.find_god_functions()
        if god_functions:
            report.append(f"\n## Complex Functions ({len(god_functions)} found)\n")
            report.append("These functions are overly complex and should be refactored:\n")
            for func in god_functions[:limit]:
                report.append(f"- **{func['name']}** in `{func['file']}`:{func['line']}")
                report.append(f"  - Lines: {func['lines']}, Calls: {func['calls']}, Complexity: {func['complexity_score']}")

        # Circular dependencies
        circular = self.find_circular_dependencies()
        if circular:
            report.append(f"\n## Circular Dependencies ({len(circular)} cycles)\n")
            report.append("These circular call chains should be broken:\n")
            for cycle in circular[:limit]:
                cycle_str = " → ".join(cycle['cycle'])
                report.append(f"- {cycle_str}")

        # Isolated modules (safe to refactor)
        isolated = self.refactoring.find_isolated_modules()
        if isolated:
            report.append(f"\n## Safe Refactoring Targets ({len(isolated)} functions)\n")
            report.append("These functions have few dependencies (safe to refactor):\n")
            for func in isolated[:limit]:
                report.append(f"- **{func['name']}** in `{func['file']}`:{func['line']}")
                report.append(f"  - Incoming: {func['incoming']}, Outgoing: {func['outgoing']}, Lines: {func['lines']}")

        return "\n".join(report)

    def generate_complexity_report(self) -> str:
        """
        Generate markdown complexity analysis report

        Returns:
            Markdown formatted report
        """
        report = ["# Complexity Analysis Report\n"]
        report.append("*Generated by CodeCompass*\n")

        # Distribution
        dist = self.analysis.get_complexity_distribution()
        if dist:
            total = dist.get('total_functions', 0)
            report.append("## Complexity Distribution\n")
            report.append(f"- **Simple** (< 10): {dist.get('simple', 0)} ({dist.get('simple', 0) * 100 // max(total, 1)}%)")
            report.append(f"- **Medium** (10-30): {dist.get('medium', 0)} ({dist.get('medium', 0) * 100 // max(total, 1)}%)")
            report.append(f"- **Complex** (30-50): {dist.get('complex', 0)} ({dist.get('complex', 0) * 100 // max(total, 1)}%)")
            report.append(f"- **Very Complex** (50+): {dist.get('very_complex', 0)} ({dist.get('very_complex', 0) * 100 // max(total, 1)}%)")
            report.append(f"\n**Average Complexity:** {dist.get('average_complexity', 0):.1f}\n")

        # Hotspots
        hotspots = self.get_complexity_hotspots(10)
        if hotspots:
            report.append("## Complexity Hotspots\n")
            report.append("Files with the most connections:\n")
            for i, file_info in enumerate(hotspots, 1):
                report.append(f"{i}. **{file_info['file']}** (Score: {file_info['hotspot_score']})")
                report.append(f"   - Entities: {file_info['entities']}, Outgoing: {file_info['outgoing']}, Incoming: {file_info['incoming']}")

        # Most called
        most_called = self.get_most_called_functions(10)
        if most_called:
            report.append("\n## Most Called Functions\n")
            for i, func in enumerate(most_called, 1):
                report.append(f"{i}. **{func['name']}** in `{func['file']}`:{func['line']} - Called {func['times_called']} times")

        return "\n".join(report)